name: pyCI
run-name: ${{ github.actor }} is testing  🚀
on: [push]
jobs:
  bilds:
    runs-on: ubuntu-latest
    steps:
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: <code_climate_reporter_id>
        with:
          coverageCommand: npm run coverage
          debug: true